stages:
  preprocess:
    cmd: venv\Scripts\python.exe src/preprocessing.py
    deps:
    - data/raw/Data_CU_venta.csv
    - src/preprocessing.py
    outs:
    - data/processed/train.csv
    - data/processed/val.csv
    - data/processed/test.csv
  train:
    cmd: venv\Scripts\python.exe src/train.py
    deps:
    - data/processed/train.csv
    - data/processed/val.csv
    - src/train.py
    outs:
    - models/model.pkl
  monitor_drift:
    cmd: venv\Scripts\python.exe src/monitor_drift.py
    deps:
    - data/processed/train.csv
    - data/processed/val.csv
    - data/processed/test.csv
    - src/monitor_drift.py
    outs:
    - output/data_drift/drift_train_vs_val.html
    - output/data_drift/drift_train_vs_test.html
    - output/data_drift/drift_val_vs_test.html
