stages:
  preprocess:
    cmd: venv\Scripts\python.exe src/preprocessing.py
    deps:
    - data/raw/Data_CU_venta.csv
    - src/preprocessing.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train:
    cmd: venv\Scripts\python.exe src/train.py
    deps:
    - data/processed/train.csv
    - src/train.py
    outs:
    - models/model.pkl
  monitor_drift:
    cmd: venv\Scripts\python.exe src/monitor_drift.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/monitor_drift.py
    outs:
    - output/data_drift/data_drift_report.html
